### ISSUE TITLE
[fusion-plugin-rpc#3] Add support for FormData

### ISSUE THREAD

**Issue by chrisdothtml** [fusionjs/fusionjs#269]
This issue was migrated from [fusionjs/fusion-plugin-rpc#3](https://github.com/fusionjs/fusion-plugin-rpc/issues/3) and was originally reported by @lhorie.

---

Rationale: Currently, RPC always assume JSON data. Supporting FormData would enable the ability to do file uploads

**Comment by joginder07** [comment]
Any update on this? I can work on this issue.

**Comment by chrisdothtml** [comment]
@joginder07 I don't think this is currently being worked on, a pr would be much appreciated!
