### ISSUE TITLE
[fusion-plugin-react-router#249] Add support for React Router v5

### ISSUE THREAD

**Issue by chrisdothtml** [fusionjs/fusionjs#273]
This issue was migrated from [fusionjs/fusion-plugin-react-router#249](https://github.com/fusionjs/fusion-plugin-react-router/issues/249) and was originally reported by @NameFILIP.

---

It should be fully compatible with v4: https://reacttraining.com/blog/react-router-v5/

**Comment by rtsao** [comment]
Closed by https://github.com/fusionjs/fusionjs/commit/4bec790253489bb9dae09270c3f8e95579d8848d
