### ISSUE TITLE
[fusion-plugin-jwt#170] Parity between Koa-Session and Fusion's JWT Session

### ISSUE THREAD

**Issue by chrisdothtml** [fusionjs/fusionjs#296]
This issue was migrated from [fusionjs/fusion-plugin-jwt#170](https://github.com/fusionjs/fusion-plugin-jwt/issues/170) and was originally reported by @saumitrabhave.

---

Other koa middlewares (For Eg. koa-passport) , which work with sessions, expect `session` to be exposed at `ctx.session` as a plain key-val object. but the JWTSession exposed by this plugin exposes session *ONLY* as a plugin service, making it impossible to integrate transparently with other koa-middlewares that work with sessions.

### Type of issue

Feature Request

### Description

When using this plugin as Session Provider in fusion app, any koa-middleware should be able to transparently use it just as if its koa's session (For Eg. `koa-session`)

Basic requirements for that would be to
1. Expose session object in context at `ctx.session`
2. session should allow access like plain object and should not mandate usage of `get` and `set` methods for working with values in session.

### Current behavior
Session can only be accessed by creating a fusion plugin and declaring dependency on JWTSession.

Miidlewares written for koa with no consideration of fusion can not access session as these libraries expect session to be exposes as property on context object.

### Expected behavior

koa-middlewares should be able to access session via context, For Eg. `ctx.session`

### Steps to reproduce
NA

### Your environment
NA

**Comment by rtsao** [comment]
Would review a PR for this.

**Comment by vincentmvdm** [comment]
I realize I'm bumping a three-year-old issue but did this ever get resolved?

I'd love to be able to use koa-passport easily (fusion-plugin-passport is unmaintained) but that doesn't seem possible due to the way fusion does sessions.
