### ISSUE TITLE
[fusion-plugin-csrf-protection-react#136] Upgrade `fusion-plugin-csrf-protection` dependency to 1.0.7

### ISSUE THREAD

**Issue by chrisdothtml** [fusionjs/fusionjs#297]
This issue was migrated from fusion-plugin-csrf-protection-react and was originally reported by @steponas.

---

### Type of issue
Bug.

### Description
The current (1.0.3 and 1.0.4-0) version of this module depends on `fusion-plugin-csrf-protection:1.0.3` which does not yet have [this commit](https://github.com/fusionjs/fusion-plugin-csrf-protection/commit/948f348819ba5ce441825dd3fb2659aa5a6b5cd5) in it.

### Current behavior
`flow check` fails with errors in the `fusion-plugin-csrf-protection` dependency.

### Expected behavior

Flow passes.

### Workaround
I did work around this by adding the working version of the dependency in `package.json -> resolutions`.

**Comment by steponas** [comment]
This does not look to be a problem any more. I suggest to close it.
