### ISSUE TITLE
[fusion-cli#504] JSON tree shaking is not supported

### ISSUE THREAD

**Issue by chrisdothtml** [fusionjs/fusionjs#333]
This issue was migrated from [fusionjs/fusion-cli#504](https://github.com/fusionjs/fusion-cli/issues/504) and was originally reported by @flyingsky.

---

### Type of issue

bug

### Description

Add `import {version} from '../package.json'` to get version from package.json and use it, but whole package.json is included in js bundle. Same code without fusion only `version` is imported and tree shaking works well.

### Current behavior

Whole json file is included in js bundle.

### Expected behavior

Only imported property should be imported.

### Steps to reproduce

1. Add `import {version} from '../package.json'` to your code and use it.
2. `yarn build-production` the whole json file is included in js bundle.

### Your environment

* fusion-cli version: 1.9.1

* Node.js version (`node --version`): 8.11.3

* npm version (`npm --version`): 5.6.0

* Operating System: Mac

**Comment by micburks** [comment]
Fixed in https://github.com/fusionjs/fusionjs/commit/b5afefeebc4f890a709eb9195e5addb85c81576f
