### ISSUE TITLE
[fusion-cli#646] Don't generate vendor chunks for async chunks

### ISSUE THREAD

**Issue by chrisdothtml** [fusionjs/fusionjs#341]
This issue was migrated from [fusionjs/fusion-cli#646](https://github.com/fusionjs/fusion-cli/issues/646) and was originally reported by @brendean.

---

### Type of issue

Feature request

### Description

Currently the config for `splitChunks.cacheGroups.vendor.chunks` is `initial` which will result in a vendor bundle being generated for a chunk (if needed). For my use case at least I would rather that all vendor files be in the vendor bundle (even before the chunk needing them is loaded).

### Current behavior

Vendor bundles can be generated for each async chunk.

### Expected behavior

All vendor code should be in the vendor bundle and chunks should only be non-vendor code (this is just my use case, I'm not sure if this is the behavior everyone would want).

### Your environment

* fusion-cli version: 1.13.0-beta.17

**Comment by rtsao** [comment]
`splitChunks` config can now be supplied
