### ISSUE TITLE
[fusion-cli#759] Add an option to avoid compiling for non-evergreen browser targets

### ISSUE THREAD

**Issue by chrisdothtml** [fusionjs/fusionjs#348]
This issue was migrated from [fusionjs/fusion-cli#759](https://github.com/fusionjs/fusion-cli/issues/759) and was originally reported by @vicapow.

---

We have some apps with large bundles. With the recent per-browser bundling, builds have gone from ~2minutes to ~14 minutes. Most of these apps are only used in internally and so we can assume they'll mostly only be using Chrome or similar evergreen browsers.

**Comment by micburks** [comment]
Added in https://github.com/fusionjs/fusionjs/pull/479
