### ISSUE TITLE
[fusion-cli#765] When using a Service Worker I get "Module not found: Error: Can't resolve 'fs'"

### ISSUE THREAD

**Issue by chrisdothtml** [fusionjs/fusionjs#350]
This issue was migrated from [fusionjs/fusion-cli#765](https://github.com/fusionjs/fusion-cli/issues/765) and was originally reported by @mcasebeer.

---

I'm currently attempting to add a service worker that does a bit more then just caching and doesn't some decompression on the worker. The decompression I'm running I have already tested and have it working outside of the service worker (just inside a fetch) without a problem. This decompression is done by the draco3D library (https://github.com/google/draco). When I attempt to load this library into my service worker I get the following error: 

Module not found: Error: Can't resolve 'fs' in '/node_modules/draco3d'

### Steps to reproduce

1. create a service worker (sw.js) and configure it follow fusionjs documents
2. add draco3d to the project
3. update src/sw.js to import draco `import draco3d from 'draco3d';`
4. attempt to run the project.

* fusion-cli version: ^1.18.3

* Node.js version (`node --version`): v8.12.0

* npm version (`npm --version`): 6.4.1

* Operating System: linux (ubuntu 14)

**Comment by micburks** [comment]
Original issue is closed https://github.com/fusionjs/fusion-cli/issues/765
