### ISSUE TITLE
[browser-tests#19] Report results back to saucelabs

### ISSUE THREAD

**Issue by chrisdothtml** [fusionjs/fusionjs#351]
This issue was migrated from [fusionjs/browser-tests#19](https://github.com/fusionjs/browser-tests/issues/19) and was originally reported by @angus-c.

---

There is a util to post results back to saucelabs but it's slow and flakey. Can probably live without it since Travis will correctly report success/fail

**Comment by micburks** [comment]
It appears a bot reopened this PR, but this package doesn't exist anymore
