### ISSUE TITLE
[create-fusion-app#50] Implement `lint` target in package.json

### ISSUE THREAD

**Issue by chrisdothtml** [fusionjs/fusionjs#364]
This issue was migrated from [fusionjs/create-fusion-app#50](https://github.com/fusionjs/create-fusion-app/issues/50) and was originally reported by @KevinGrandon.

---

Let's ship with eslint-config-fusion and the `lint` target.

**Comment by micburks** [comment]
There is a lint script, just needs to be fixed at the moment
