### ISSUE TITLE
[fusion-plugin-react-helmet-async] Helmet is undefined 

### ISSUE THREAD

**Issue by Monar** [fusionjs/fusionjs#436]
In version `fusion-plugin-react-helmet-async@2.0.0` Helmet is incorrectly exported :(

```
import {Helmet} from 'fusion-plugin-react-helmet-async';
// Helmet === undefined :(
```

https://stackblitz.com/edit/react-685lpp

**Comment by KevinGrandon** [comment]
Thanks for filing. It looks like we changed imports according to react-async-helmet, but that was according to a version we're not using yet.
