### ISSUE TITLE
flow 0.96 / fusion-plugin-react-router@2.0.2: modules/ServerHistory.js error: "Cannot import `createPath` because there is no `createPath` export in `history`."

### ISSUE THREAD

**Issue by lxe** [fusionjs/fusionjs#475]
This is in fusion-plugin-react-router@2.0.2
Which depends on history 4.9.0

```
=> Found "history@4.9.0"
info Has been hoisted to "history"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "fusion-plugin-react-router#history"
   - Hoisted from "fusion-plugin-react-router#react-router-dom#history"
```

Get:

```
Cannot import `createPath` because there is no `createPath` export in `history`.
Cannot import `parsePath` because there is no `parsePath` export in `history`.
```

On https://github.com/fusionjs/fusionjs/blob/10b64c280d4acc76ed0639e21e05fc12be15b318/fusion-plugin-react-router/src/modules/ServerHistory.js#L9

--- 

history@4.9.0 https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/history_v4.9.x/flow_v0.25.x-/history_v4.9.x.js : no createPath in libdef

	
However https://github.com/ReactTraining/history/blob/5f367d8cbdaf91d7f64e2efdbb9196feb0859f3f/modules/index.js#L5

Is the libdef wrong? Should I not use it?

**Comment by AlexMSmithCA** [comment]
`fusion-plugin-react-router` has an altered libdef for `history` which includes these missing imports: https://github.com/fusionjs/fusionjs/blob/master/fusion-plugin-react-router/flow-typed/npm/history_v4.9.x.js#L138

I'd recommend either copying it into your own project, or pointing to it via your `.flowconfig`'s `[lib]` option.

Ideally we recontribute back to flow-typed in this case.  I'll file an issue for that as well.

**Comment by AlexMSmithCA** [comment]
Closing this in favor of internally tracked issue: [WPT-3573](https://jeng.uberinternal.com/browse/WPT-3573).

**Comment by lxe** [comment]
I think this is unrelated to anything internal. Keep this open and tracked until flow-typed fixes their libdef, or fix ServerHistory.js
