### ISSUE TITLE
[fusion-test-utils] support jest's test(str, fn, timeout) signature

### ISSUE THREAD

**Issue by lxe** [fusionjs/fusionjs#476]
```
import { test } from 'fusion-test-utils';
test('no bugs', async foo => { /* ... */ }, timeout);
```

yields

```
Flow:
Cannot call `test` because no more than 2 arguments are expected by  function type [1].
```

Because
https://github.com/fusionjs/fusionjs/blob/10b64c280d4acc76ed0639e21e05fc12be15b318/fusion-test-utils/src/index.js#L88

Is missing `timeout` arg

Even though

https://github.com/fusionjs/fusionjs/blob/10b64c280d4acc76ed0639e21e05fc12be15b318/fusion-test-utils/src/index.js#L101

**Comment by lxe** [comment]
A "workaround" for now:

```js
import * as fusionTestUtils from 'fusion-test-utils';

type $Arguments<F> = $Call<<A: $ReadOnlyArray<mixed>>((...A) => mixed) => A, F>;

type FixedTest = (
  ...args: $Call<
    <A, B, C>(a: [A, B], b?: C) => [A, B, C] | [A, B],
    $Arguments<typeof fusionTestUtils.test>,
    number
  >
) => $Call<typeof fusionTestUtils.test, any, any> | typeof fusionTestUtils.test;

const test: FixedTest = (fusionTestUtils.test: any);
```

**Comment by AlexMSmithCA** [comment]
I'm not a huge fan of our wrapping of Jest here to mimic Tape.  Fixing this particular case (above) but we should explore a longer-term plan to replace and deprecate this.
