### ISSUE TITLE
Fetch should allow null and undefined as second argument

### ISSUE THREAD

**Issue by shannonmoeller** [fusionjs/fusionjs#498]
The type definition for Fetch should allow `init` to be a null or undefined value. This accurately reflects how `window.fetch()` works in-browser and would allow functions that use `fetch` internally to optionally accept options.

```diff
export type Fetch = (
  input: string | Request,
-  init?: RequestOptions
+  init?: ?RequestOptions
) => Promise<Response>;
```

https://github.com/fusionjs/fusionjs/blob/aa9ecbdf68850ddf5d9d7452cac0a58afe44a02b/fusion-tokens/src/index.js#L9

**Comment by AlexMSmithCA** [comment]
I'm not sure if we want to make this change.  For what it's worth, the current type definition for `fetch` matches that [shipped with Flow](https://github.com/facebook/flow/blob/8aa9f7c6a8d9da6e590f43de8556a6458aaae144/lib/bom.js#L1464), [the fetch standard](https://fetch.spec.whatwg.org/#fetch-method), and the community defined [node-fetch](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/node-fetch_v2.x.x/flow_v0.100.x-/node-fetch_v2.x.x.js#L106) types from the flow-typed project.

Can you provide more details or examples on how this matches what we'd expect from `window.fetch()`?

**Comment by shannonmoeller** [comment]
I'm no longer using the pattern that required this, so I don't have a good example at hand and won't push for the feature (even if I still agree with the recommendation 😄 ).
