### ISSUE TITLE
fusion-plugin-csrf-protection always uses "x" as token

### ISSUE THREAD

**Issue by slonoed** [fusionjs/fusionjs#516]
These two lines
https://github.com/fusionjs/fusionjs/commit/fcf372f3ae6185364f283ef2e71620c0b1c0a9e9#diff-bc2317ee8cff3b88c4d4c9ff63b9a581R28
https://github.com/fusionjs/fusionjs/commit/fcf372f3ae6185364f283ef2e71620c0b1c0a9e9#diff-f0eb7c8dc0875f6003c861d54fa3c233R31

Is it correct?

**Comment by slonoed** [comment]
Here is the explanation: https://github.com/fusionjs/fusion-plugin-csrf-protection/pull/157

**Comment by AlexMSmithCA** [comment]
Closing this as resolved.

**Comment by rolyatmax** [comment]
Are we planning on fixing this? It should probably be considered dangerous to have a CSRF Protection plugin that doesn't actually do a CSRF check. Anyone who uses this likely believes their endpoints are protected. And given this is an open-source project, it gives malicious actors a blueprint for where vulnerabilities might lie.

**Comment by AlexMSmithCA** [comment]
I believer this plugin works as intended.

For some additional context, we used to generate and validate a token prior to the simplified approach proposed by @ganemone above.

The custom headers approach should be sufficient protection.  Check out [this Stack answer](https://security.stackexchange.com/questions/23371/csrf-protection-with-custom-headers-and-without-validating-token) for a more thorough explanation.

**Comment by rolyatmax** [comment]
Ahhh gotcha - I wasn't aware of this mitigation technique, and I misunderstood [this comment](https://github.com/fusionjs/fusionjs/commit/fcf372f3ae6185364f283ef2e71620c0b1c0a9e9#diff-f0eb7c8dc0875f6003c861d54fa3c233R30) to mean we needed to fix the current implementation. Would it be worth us adding a comment in the code linking to this explanation you've shared? I'm happy to submit the PR if you're open to the idea.

**Comment by AlexMSmithCA** [comment]
Sure!  PRs are always welcome.  Feel free to drop a comment in [~Web Platform](https://uchat.uberinternal.com/uber/channels/web-platform) to get some 👀on the PR.
