### ISSUE TITLE
Add options for disabling zopfli and brotli to the fusionrc file

### ISSUE THREAD

**Issue by vicapow** [fusionjs/fusionjs#583]

**Comment by mlmorg** [comment]
Are there reasons for this? Is this only during local build or something, or would you want to do this for a prod build too?

**Comment by vicapow** [comment]
We'd want this for local and production. The issue is to mitigate performance degradations in previous fusion-cli versions and give users the flexibility of enabling them if they're willing to take the performance hit.

**Comment by micburks** [comment]
Closed by https://github.com/fusionjs/fusionjs/pull/606
