### ISSUE TITLE
Usage with typescript

### ISSUE THREAD

**Issue by andreimc** [fusionjs/fusionjs#635]
I am just wondering is this easy to use with typescript?

**Comment by AlexMSmithCA** [comment]
Typescript is not supported as a first-class citizen today.  It is possible however, here's some information on using typescript with Fusion.js.

https://github.com/chrisgervang/fusion-cli
https://docs.google.com/document/d/1yBUyxk_kDcXrhC6S-WvjxcsgGIVpATEXQ60UcFIEQeY/edit

Fusion.js also provides Flow types out-of-the-box.  If you would prefer TypeScript, feel free to convert those types as an alternative!
