### ISSUE TITLE
Possible bug in fusion apollo

### ISSUE THREAD

**Issue by slonoed** [fusionjs/fusionjs#674]
1) `ApolloClientPlugin` resolves to function `(ctx: Context, initialState:mixed) => ApolliClient`
https://github.com/fusionjs/fusionjs/blob/7fa468b3c361832d94db71b1ac3ba6357b739046/fusion-plugin-apollo/src/apollo-client/index.js#L134

2) FusionPluginApollo passes `requestContext.context` instead
https://github.com/fusionjs/fusionjs/blob/master/fusion-plugin-apollo/src/plugin.js#L130
Where `requestContext` has type `GraphQLRequestContext<TContext>` and `requestContext.context` has generic type `TContext` which is a graphql context and not fusion context.

The problem is that `TContext` is used as `Context` and apollo client plugin tries to use things like `ctx.memoized`.

**Comment by slonoed** [comment]
## More details on this

This issue happened when custom apollo context is used by setting `ApolloContextToken` to function. To reproduce crete a new app and add context getter
```
import {ApolloContextToken} from 'fusion-plugin-apollo'
// ...
app.register(ApolloContextToken, () => ({
    myContext: true
}))
```

[ Documentation says](https://github.com/fusionjs/fusionjs/tree/master/fusion-plugin-apollo#apollocontexttoken): 
> A function which returns the apollo context. Defaults to the fusion context.

However `executor` [function](https://github.com/fusionjs/fusionjs/blob/master/fusion-plugin-apollo/src/plugin.js#L130) assumes context is allways fusion context.

**Comment by ganemone** [comment]
Thanks for bringing this up! Added a fix for this here: https://github.com/fusionjs/fusionjs/commit/fa877ad95f2b8ba336e7ea625bfcce380dfa4980
