### ISSUE TITLE
 fusion-plugin-rpc-react-redux declares fusion-plugin-rpc wrongly as peer-dependency

### ISSUE THREAD

**Issue by arun-uber** [fusionjs/fusionjs#685]
I found a bug in fusion-plugin-rpc-react-redux.

In package.json of fusion-plugin-rpc-react-redux,

Actual: 
fusion-plugin-rpc is declared as a peer-dependency of fusion-plugin-rpc-react-redux.

Expected.
fusion-plugin-rpc is declared as a dependency of fusion-plugin-rpc-react-redux.

**Comment by mlmorg** [comment]
This is actually correct. It is a peer dependency. We include fusion-plugin-rpc as a top-level dependency in the scaffold.

**Comment by arunkandregula** [comment]
That breaks the code if we build a fusion app from open source fusion. This is because, fusion-plugin-rpc has peer dependencies as fusion-plugin-universal-events, fusion-plugin-i18n, which are supposed to be installed as dependencies for fusion app.

**Comment by arunkandregula** [comment]
If fusion-plugin-rpc  is a dependency, then we dont have to install fusion-plugin-universal-events, fusion-plugin-i18n. If  fusion-plugin-rpc is a peer dependency, we have to install fusion-plugin-universal-events, fusion-plugin-i18n. In practice, users are not supposed to deal with them. So their code breaks if they dont install fusion-plugin-universal-events, fusion-plugin-i18n.

**Comment by arunkandregula** [comment]
+ @ganemone
