### ISSUE TITLE
[fusion-plugin-error-handling] cross origin script errors

### ISSUE THREAD

**Issue by foodforarabbit** [fusionjs/fusionjs#698]
there is no way to change or add information to the errors being logged.

There are lot of these "Script error." logs showing up and we want to add some additional data to the error to help us debug the issue. We want to add information such as the url or some cookie information. We can do this by passing in a function that can transform / augment the data passed to the error handler.

https://blog.sentry.io/2016/05/17/what-is-script-error

pr: https://github.com/fusionjs/fusionjs/pull/697

**Comment by micburks** [comment]
Closing as per discussion in the linked PR
