### ISSUE TITLE
[fusion-plugin-i18n] TranslateFuncType does not accept {[string]: string} as parameter

### ISSUE THREAD

**Issue by foodforarabbit** [fusionjs/fusionjs#701]
Currently the type is 

```
export type TranslateFuncType = (
  key: string,
  interpolations?: {[string]: string | number}
) => string;
```

which does not accept {[string]: string} as an argument, since it might mutate the parameter which would violate the type of the variable being passed in.

By changing the type to read-only {+[string]: string | number} it allows the function to accept {[string]: string} as expected.

**Comment by micburks** [comment]
The referencing PR has been merged. Thanks!
