### ISSUE TITLE
ReferenceError: Helmet is not defined

### ISSUE THREAD

**Issue by chilupa** [fusionjs/fusionjs#711]
I was building a Todo app referring to Fusion.js [docs](https://fusionjs.com/docs/learning-fusionjs-tutorial/building-the-ui#optional-styling) 

I added `fusion-plugin-react-helmet-async` plugin using `yarn` but it seem to have an error.

I tried to import *Helmet* but that does not seem to work. Is there something that I'm missing.  Could anyone please help? 

**Code**

```
import React, { useState } from "react";

const Root = () => {
  const [todos, setTodos] = useState([]);
  const [inputText, setInputText] = useState("");

  ...

  return (
    <React.Fragment>
      <Helmet>
        <style>
          {`
        body {
          background-color: #f5f5f5;
          font: 24px 'Helvetica Neue', Helvetica, Arial, sans-serif;
        }
      `}
        </style>
      </Helmet>
      <h1>todos</h1>
      <div className="container">
        ...
      </div>
    </React.Fragment>
  );
};

export default <Root />;

```

**Error Message**

[![error-on-browser][1]][1]

  [1]: https://i.stack.imgur.com/R3hle.png

**Comment by derekju** [comment]
@chilupa: Did you import the Helmet component?

```
import {Helmet} from 'fusion-plugin-react-helmet-async';
```

**Comment by derekju** [comment]
I just noticed that the example is missing this import so I will add it.

**Comment by derekju** [comment]
https://github.com/fusionjs/fusionjs.github.io/pull/163

**Comment by chilupa** [comment]
Adding the _import_ statement worked!
