### ISSUE TITLE
[i18n plugin] Result of useTranslations() can't be passed to React hook

### ISSUE THREAD

**Issue by akre54** [fusionjs/fusionjs#737]
Minimal repro:

```
function MyComponent() {
  const t = useTranslations();
  const onClick = useCallback(() => {
    const message = t('say_hello');
    alert(message);
  }, [t])

  return <div onClick={onClick} />;
}
```

The i18n babel plugin fails with `Unexpected usage of useTranslations return function`. Seems to be because of [this line](https://github.com/fusionjs/fusionjs/blob/70ecbc5a83286b98cf485729fa4ff8d6a434899c/fusion-cli/build/babel-plugins/babel-plugin-i18n/index.js#L62-L65) since `translationPath.parent` is an `ArrayExpression`.

**Comment by akre54** [comment]
Also, is it possible to add line position info to the Error thrown here? Hard to track down the issue without diving into the plugin unfortunately :/

**Comment by micburks** [comment]
This was fixed in https://github.com/fusionjs/fusionjs/commit/353233355f5f282c5c48fbce36abc3189848a99b. Upgrade to the latest and you shouldn't have this issue anymore

**Comment by akre54** [comment]
Yep! Updating fusion-cli fixed it. Thanks!

Still holding out hope for more line number info in the future (just passing along `translationPath.pos` would be huge!), but thanks for the quick fix!

**Comment by micburks** [comment]
> Yep! Updating fusion-cli fixed it. Thanks!
> 
> Still holding out hope for more line number info in the future (just passing along `translationPath.pos` would be huge!), but thanks for the quick fix!

Yeah that's a good idea. I'll make a ticket to investigate. Thanks!
