### ISSUE TITLE
fusion-cli dependents on insecure "bl" module

### ISSUE THREAD

**Issue by jowcy** [fusionjs/fusionjs#757]
It appears that the "bl" library recently issued updates to their 2.x, 3.x, and 4.x lines to close a security hole.  The "bl" library owners have chosen to not apply this fix back to the 1.x line, see https://github.com/rvagg/bl/issues/52

fusion-cli indirectly depends on bl@^1.0.0 via this path of node libraries iltorb / prebuild-install / tar-fs / tar-stream

yarn why bl results with
=> Found "bl@1.2.2"
info Has been hoisted to "bl"
info Reasons this module exists
   - Hoisted from "@uber#fusion-plugin-rosetta#@uber#node-rosetta#decompress#decompress-tar#tar-stream#bl"
   - Hoisted from "fusion-cli#iltorb#prebuild-install#tar-fs#tar-stream#bl"
   
Note that there is no updated version of iltorb because that library is deprecated, see https://www.npmjs.com/package/iltorb

**Comment by jowcy** [comment]
Also note that attempting to force bl to resolve to a higher version (either 3.0.1 or 2.2.1) causes runtime errors with a fusion based application.

Error: Cannot register undefined without a token. Did you accidentally register a browser plugin on the server?
at App.FusionApp._defineProperty [as register] (.../node_modules/fusion-core/dist-node-cjs/base-app.js:65:13)

**Comment by voodoologic** [comment]
This is a cross cutting issue for various teams at my org as it represents a [security concern](https://hackerone.com/reports/966347).  I'm interested in its resolution.

**Comment by rtsao** [comment]
Regarding fusion-cli, this was fixed in https://github.com/fusionjs/fusionjs/commit/7535384c9c2f6152e02a564282478d3b2e9fa335

As for `@uber/node-rosetta`, this has also since been updated in the newest version. Update your lockfiles accordingly.

Marking as resolved.
